---
  # This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  tasks:
  - name: Inspect Splunk UF facts
    win_stat:
      path: "{{ splunk_installdir_windows }}"
    register: status

  - name: Verify Splunk UF is installed
    assert:
      that: "status.stat.exists is true"  